IDIR =./include
CC=g++
CFLAGS=-I$(IDIR)

ODIR =.
SDIR =./src

LIBS=-lopengl32 -lGLU32 -lglut32

_DEPS = Camera.h Global.h Header.h ViewingMode.h Vec3.h Geometry.h Utils.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))


_OBJ = Camera.o main.o Global.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))


$(ODIR)/%.o: $(SDIR)/%.cpp
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $< 

all: aurua

aurua: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f $(ODIR)/*.o *~ core $(INCDIR)/*~ aurua

